version: '3.8'

services:
  pgair-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgair-db
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgair
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
